config/routes.rb
Rails.application.routes.draw do
  resources :flowers
  root 'pages#index'
  get 'pages/index'

  resources :bodies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/body.rb
class Body < ApplicationRecord
  after_validation :predict_gender

  def predict_gender
    features = [
      self.weight,
      self.stature,
      self.head_circumference,
      self.shoulder_breadth,
      self.hand_length,
      self.hand_breadth,
      self.chest_circumference,
      self.waist_circumference,
      self.foot_length,
      self.foot_breadth,
      self.age
    ]

    prediction = BodyAi.predict([features])
    self.gender = prediction[:humanized_prediction]
  end
end

app/models/body_ai.rb
class BodyAi < ApplicationRecord
  include Dnnff::ActsAsDnnModeler

  acts_as_dnn_modeler architecture: [
    [11, ''],
    [32, 'relu'],
    [64, 'relu'],
    [64, 'relu'],
    [64, 'relu'],
    [32, 'relu'],
    [2, 'softmax']
  ], output_classes: ["Male", "Female"]

  self.abstract_class = true
end

app/models/flower.rb
class Flower < ApplicationRecord
  after_validation :predict_specie

  def predict_specie
    features = [
      self.sepal_length,
      self.sepal_width,
      self.petal_length,
      self.petal_width,
    ]

    prediction = FlowerAi.predict([features])
    self.specie = prediction[:humanized_prediction]
  end
end

app/models/flower_ai.rb
class FlowerAi < ApplicationRecord
  include Dnnff::ActsAsDnnModeler

  acts_as_dnn_modeler architecture: [
    [4, ''],
    [64, 'relu'],
    [128, 'relu'],
    [128, 'relu'],
    [64, 'relu'],
    [3, 'softmax']
  ], output_classes: ['Setosa', 'Versicolor', 'Virginica']

  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/bodies_controller.rb
class BodiesController < ApplicationController
  before_action :set_body, only: [:show, :edit, :update, :destroy]

  # GET /bodies
  # GET /bodies.json
  def index
    @bodies = Body.all
  end

  # GET /bodies/1
  # GET /bodies/1.json
  def show
  end

  # GET /bodies/new
  def new
    @body = Body.new
  end

  # GET /bodies/1/edit
  def edit
  end

  # POST /bodies
  # POST /bodies.json
  def create
    @body = Body.new(body_params)

    respond_to do |format|
      if @body.save
        format.html { redirect_to @body, notice: 'Body was successfully created.' }
        format.json { render :show, status: :created, location: @body }
      else
        format.html { render :new }
        format.json { render json: @body.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bodies/1
  # PATCH/PUT /bodies/1.json
  def update
    respond_to do |format|
      if @body.update(body_params)
        format.html { redirect_to @body, notice: 'Body was successfully updated.' }
        format.json { render :show, status: :ok, location: @body }
      else
        format.html { render :edit }
        format.json { render json: @body.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bodies/1
  # DELETE /bodies/1.json
  def destroy
    @body.destroy
    respond_to do |format|
      format.html { redirect_to bodies_url, notice: 'Body was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_body
      @body = Body.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def body_params
      params.require(:body).permit(:full_name, :weight, :stature, :head_circumference, :shoulder_breadth, :hand_length, :hand_breadth, :chest_circumference, :waist_circumference, :foot_length, :foot_breadth, :age, :gender)
    end
end

app/controllers/flowers_controller.rb
class FlowersController < ApplicationController
  before_action :set_flower, only: [:show, :edit, :update, :destroy]

  # GET /flowers
  # GET /flowers.json
  def index
    @flowers = Flower.all
  end

  # GET /flowers/1
  # GET /flowers/1.json
  def show
  end

  # GET /flowers/new
  def new
    @flower = Flower.new
  end

  # GET /flowers/1/edit
  def edit
  end

  # POST /flowers
  # POST /flowers.json
  def create
    @flower = Flower.new(flower_params)

    respond_to do |format|
      if @flower.save
        format.html { redirect_to @flower, notice: 'Flower was successfully created.' }
        format.json { render :show, status: :created, location: @flower }
      else
        format.html { render :new }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flowers/1
  # PATCH/PUT /flowers/1.json
  def update
    respond_to do |format|
      if @flower.update(flower_params)
        format.html { redirect_to @flower, notice: 'Flower was successfully updated.' }
        format.json { render :show, status: :ok, location: @flower }
      else
        format.html { render :edit }
        format.json { render json: @flower.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flowers/1
  # DELETE /flowers/1.json
  def destroy
    @flower.destroy
    respond_to do |format|
      format.html { redirect_to flowers_url, notice: 'Flower was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flower
      @flower = Flower.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flower_params
      params.require(:flower).permit(:sepal_length, :sepal_width, :petal_length, :petal_width, :specie)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bodies_helper.rb
module BodiesHelper
end

app/helpers/flowers_helper.rb
module FlowersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/bodies/_form.html.erb
<%= form_for(body) do |f| %>
  <% if body.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(body.errors.count, "error") %> prohibited this body from being saved:</h2>

      <ul>
      <% body.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :full_name %>
    <%= f.text_field :full_name %>
  </div>

  <div class="field">
    <%= f.label :weight %>
    <%= f.number_field :weight %>
  </div>

  <div class="field">
    <%= f.label :stature %>
    <%= f.number_field :stature %>
  </div>

  <div class="field">
    <%= f.label :head_circumference %>
    <%= f.number_field :head_circumference %>
  </div>

  <div class="field">
    <%= f.label :shoulder_breadth %>
    <%= f.number_field :shoulder_breadth %>
  </div>

  <div class="field">
    <%= f.label :hand_length %>
    <%= f.number_field :hand_length %>
  </div>

  <div class="field">
    <%= f.label :hand_breadth %>
    <%= f.number_field :hand_breadth %>
  </div>

  <div class="field">
    <%= f.label :chest_circumference %>
    <%= f.number_field :chest_circumference %>
  </div>

  <div class="field">
    <%= f.label :waist_circumference %>
    <%= f.number_field :waist_circumference %>
  </div>

  <div class="field">
    <%= f.label :foot_length %>
    <%= f.number_field :foot_length %>
  </div>

  <div class="field">
    <%= f.label :foot_breadth %>
    <%= f.number_field :foot_breadth %>
  </div>

  <div class="field">
    <%= f.label :age %>
    <%= f.number_field :age %>
  </div>

  <div class="field">
    <%= f.label :gender %>
    <%= f.text_field :gender %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bodies/edit.html.erb
<h1>Editing Body</h1>

<%= render 'form', body: @body %>

<%= link_to 'Show', @body %> |
<%= link_to 'Back', bodies_path %>

app/views/bodies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Bodies</h1>

<table>
  <thead>
    <tr>
      <th>Full name</th>
      <th>Weight</th>
      <th>Stature</th>
      <th>Head circumference</th>
      <th>Shoulder breadth</th>
      <th>Hand length</th>
      <th>Hand breadth</th>
      <th>Chest circumference</th>
      <th>Waist circumference</th>
      <th>Foot length</th>
      <th>Foot breadth</th>
      <th>Age</th>
      <th>Gender</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @bodies.each do |body| %>
      <tr>
        <td><%= body.full_name %></td>
        <td><%= body.weight %></td>
        <td><%= body.stature %></td>
        <td><%= body.head_circumference %></td>
        <td><%= body.shoulder_breadth %></td>
        <td><%= body.hand_length %></td>
        <td><%= body.hand_breadth %></td>
        <td><%= body.chest_circumference %></td>
        <td><%= body.waist_circumference %></td>
        <td><%= body.foot_length %></td>
        <td><%= body.foot_breadth %></td>
        <td><%= body.age %></td>
        <td><%= body.gender %></td>
        <td><%= link_to 'Show', body %></td>
        <td><%= link_to 'Edit', edit_body_path(body) %></td>
        <td><%= link_to 'Destroy', body, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Body', new_body_path %>

app/views/bodies/new.html.erb
<h1>New Body</h1>

<%= render 'form', body: @body %>

<%= link_to 'Back', bodies_path %>

app/views/bodies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @body.full_name %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @body.weight %>
</p>

<p>
  <strong>Stature:</strong>
  <%= @body.stature %>
</p>

<p>
  <strong>Head circumference:</strong>
  <%= @body.head_circumference %>
</p>

<p>
  <strong>Shoulder breadth:</strong>
  <%= @body.shoulder_breadth %>
</p>

<p>
  <strong>Hand length:</strong>
  <%= @body.hand_length %>
</p>

<p>
  <strong>Hand breadth:</strong>
  <%= @body.hand_breadth %>
</p>

<p>
  <strong>Chest circumference:</strong>
  <%= @body.chest_circumference %>
</p>

<p>
  <strong>Waist circumference:</strong>
  <%= @body.waist_circumference %>
</p>

<p>
  <strong>Foot length:</strong>
  <%= @body.foot_length %>
</p>

<p>
  <strong>Foot breadth:</strong>
  <%= @body.foot_breadth %>
</p>

<p>
  <strong>Age:</strong>
  <%= @body.age %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @body.gender %>
</p>

<%= link_to 'Edit', edit_body_path(@body) %> |
<%= link_to 'Back', bodies_path %>

app/views/flowers/_form.html.erb
<%= form_for(flower) do |f| %>
  <% if flower.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(flower.errors.count, "error") %> prohibited this flower from being saved:</h2>

      <ul>
      <% flower.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sepal_length %>
    <%= f.text_field :sepal_length %>
  </div>

  <div class="field">
    <%= f.label :sepal_width %>
    <%= f.text_field :sepal_width %>
  </div>

  <div class="field">
    <%= f.label :petal_length %>
    <%= f.text_field :petal_length %>
  </div>

  <div class="field">
    <%= f.label :petal_width %>
    <%= f.text_field :petal_width %>
  </div>

  <div class="field">
    <%= f.label :specie %>
    <%= f.text_field :specie %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flowers/edit.html.erb
<h1>Editing Flower</h1>

<%= render 'form', flower: @flower %>

<%= link_to 'Show', @flower %> |
<%= link_to 'Back', flowers_path %>

app/views/flowers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flowers</h1>
<%= link_to "Flower sample data", "https://github.com/mwaskom/seaborn-data/blob/master/iris.csv", target: "_blank" %>

</br>
</br>

<table>
  <thead>
    <tr>
      <th>Sepal length</th>
      <th>Sepal width</th>
      <th>Petal length</th>
      <th>Petal width</th>
      <th>Specie</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flowers.each do |flower| %>
      <tr>
        <td><%= flower.sepal_length %></td>
        <td><%= flower.sepal_width %></td>
        <td><%= flower.petal_length %></td>
        <td><%= flower.petal_width %></td>
        <td><%= flower.specie %></td>
        <td><%= link_to 'Show', flower %></td>
        <td><%= link_to 'Edit', edit_flower_path(flower) %></td>
        <td><%= link_to 'Destroy', flower, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flower', new_flower_path %>

app/views/flowers/new.html.erb
<h1>New Flower</h1>

<%= render 'form', flower: @flower %>

<%= link_to 'Back', flowers_path %>

app/views/flowers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sepal length:</strong>
  <%= @flower.sepal_length %>
</p>

<p>
  <strong>Sepal width:</strong>
  <%= @flower.sepal_width %>
</p>

<p>
  <strong>Petal length:</strong>
  <%= @flower.petal_length %>
</p>

<p>
  <strong>Petal width:</strong>
  <%= @flower.petal_width %>
</p>

<p>
  <strong>Specie:</strong>
  <%= @flower.specie %>
</p>

<%= link_to 'Edit', edit_flower_path(@flower) %> |
<%= link_to 'Back', flowers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Measurements</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <footer style="font-size: 2rem; position:absolute; bottom:20px; right: 20px">
      <%= link_to "View code in Github", "https://github.com/GabrielSandoval/dnnff_rails_example" %>
    </footer>
  </body>
</html>

app/views/pages/index.html.erb
<h1> Measurements </h1>

<%= link_to "Body", bodies_path %>
</br>
<%= link_to "Flowers", flowers_path %>